## Useful commands
# docker-compose up -d
# docker-compose down

## To stop single containers from compose
# docker-compose rm -sv <service name>
# docker rmi -f <image_id> # to remove image
# docker-compose up -d  # to rebuild only that image you removed (built images wont be rebuilt)

## To remove images
# docker images -q
# copy and paste ids and use docker rmi


version: "3.8"

volumes:
  rabbitmq_data:

networks:
  default:
    name: kong_kong-net

services:
  #######################################################################
  # Simple microservices
  #######################################################################


  ####################################
  # Item microservice
  ####################################
  item:
    build:
      context: ./item
      dockerfile: item.Dockerfile
    image: vickyyqu/item:esd
    restart: always
    environment:
      PYTHONUNBUFFERED: 1
    ports:
      - "5000:5000"



  ####################################
  # Company microservice
  ####################################
  company:
    build:
      context: ./company
      dockerfile: company.Dockerfile
    image: vickyyqu/company:esd
    restart: always
    environment:
      PYTHONUNBUFFERED: 1
    ports:
      - "5001:5001"


  ####################################
  # Department microservice
  ####################################
  department:
    platform: linux/amd64
    build:
      context: ./department
      dockerfile: Dockerfile
    image: vickyyqu/department:esd
    restart: always
    ports:
      - "8080:8080"

  ####################################
  # Carbon Retriever microservice
  ####################################
  carbon_retriever:
    build:
      context: ./carbon_retriever
      dockerfile: carbon_retriever.Dockerfile
    image: vickyyqu/carbon_retriever:esd
    restart: always
    environment:
      PYTHONUNBUFFERED: 1
    ports:
      - "5002:5002"

  ####################################
  # Slack microservice
  ####################################  
  # ports:
  #   - "5008:5008"



  ####################################
  # Error microservice
  ####################################  
  error:
    build:
      context: ./error
      dockerfile: error.Dockerfile
    image: vickyyqu/error:esd
    restart: always
    depends_on:
      - rabbitmq
    environment:
      rabbit_host: rabbitmq
      rabbit_port: 5672
      PYTHONUNBUFFERED: 1

  ####################################
  # Activity Log microservice
  ####################################  
  activity_log:
    build:
      context: ./activity_log
      dockerfile: activity_log.Dockerfile
    image: vickyyqu/activity_log:esd
    restart: always
    depends_on:
      - rabbitmq
    environment:
      rabbit_host: rabbitmq
      rabbit_port: 5672
      PYTHONUNBUFFERED: 1

  #######################################################################
  # Message broker microservices
  #######################################################################

  ####################################
  # RabbitMQ: The messaging broker   
  ####################################
  rabbitmq:
    image: rabbitmq:3-management
    hostname: esd-rabbit
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes: 
      - rabbitmq_data:/var/lib/rabbitmq


  ####################################
  # Kafka
  ####################################








  #######################################################################
  # Complex microservices
  ####################################################################### 



  ###############################################
  # Place Item
  ###############################################
  place_item:
    build:
      context: ./complex
      dockerfile: place_item.Dockerfile
    image: vickyyqu/place_item:esd
    restart: always
    depends_on:
      - department
      - carbon_retriever
      - item
      - activity_log
      - error
      - rabbitmq
    environment:
      rabbit_host: rabbitmq
      rabbit_port: 5672
      PYTHONUNBUFFERED: 1
      department_URL: http://department:8080/department
      carbon_retriever_URL: http://carbon_retriever:5002/search
      item_URL: http://item:5000/create
    ports:
      - "5006:5006"


  ###############################################
  # Accept Item
  ###############################################
  accept_item:
    build:
      context: ./complex
      dockerfile: accept_item.Dockerfile
    image: vickyyqu/accept_item:esd
    restart: always
    depends_on:
      - department
      - item
      - activity_log
      - error
      - rabbitmq
    environment:
      rabbit_host: rabbitmq
      rabbit_port: 5672
      PYTHONUNBUFFERED: 1
      department_URL: http://department:8080/department
      item_URL: http://item:5000
      slack_URL: http://slack:5008/slack
    ports:
      - "5101:5101"


  ###############################################
  # Reject Item
  ###############################################
  # reject_item:
  #   build:
  #     context: ./complex
  #     dockerfile: reject_item.Dockerfile
  #   image: vickyyqu/reject_item:esd
  #   restart: always
  #   environment:
  #     PYTHONUNBUFFERED: 1
  #   ports:
  #     - "5102:5102"

  
  
  #########################################
  # Get Items By Company
  ###############################################
  get_items_by_company:
    build:
      context: ./complex
      dockerfile: get_items_by_company.Dockerfile
    image: vickyyqu/get_items_by_company:esd
    restart: always
    depends_on:
      - department
      - item
      - company
      - activity_log
      - error
      - rabbitmq
    environment:
      rabbit_host: rabbitmq
      rabbit_port: 5672
      PYTHONUNBUFFERED: 1
      department_URL: http://department:8080/department
      item_URL: http://item:5000
      company_URL: http://company:5001
    ports:
      - "5003:5003"