## Useful commands
# docker-compose up -d
# docker-compose down

## To stop single containers from compose
# docker-compose rm -sv <service name>
# docker rmi -f <image_id> # to remove image
# docker-compose up -d  # to rebuild only that image you removed (built images wont be rebuilt)

## To remove images
# docker images -q
# copy and paste ids and use docker rmi


version: "3.8"

volumes:
  rabbitmq_data:

networks:
  default:
    name: kong_kong-net

services:
  #######################################################################
  # Simple microservices
  #######################################################################


  ####################################
  # Item microservice
  ####################################
  item:
    build:
      context: ./item
      dockerfile: item.Dockerfile
    image: vickyyqu/item:esd
    restart: always
    environment:
      PYTHONUNBUFFERED: 1
    ports:
      - "5000:5000"



  ####################################
  # Company microservice
  ####################################
  company:
    build:
      context: ./company
      dockerfile: company.Dockerfile
    image: vickyyqu/company:esd
    restart: always
    environment:
      PYTHONUNBUFFERED: 1
    ports:
      - "5001:5001"


  ####################################
  # Department microservice
  ####################################
  department:
    platform: linux/amd64
    build:
      context: ./department
      dockerfile: Dockerfile
    image: bryantjj/department:esd
    restart: always
    ports:
      - "8080:8080"

  ####################################
  # Carbon Retriever microservice
  ####################################
  carbon_retriever:
    build:
      context: ./carbon_retriever
      dockerfile: carbon_retriever.Dockerfile
    image: vickyyqu/carbon_retriever:esd
    restart: always
    environment:
      PYTHONUNBUFFERED: 1
    ports:
      - "5002:5002"

  ####################################
  # Slack microservice
  ####################################  
  slack:
    build:
      context: ./slack
      dockerfile: slack.Dockerfile
    image: vickyyqu/slack:esd
    restart: always
    depends_on:
      - broker
    environment:
      PYTHONUNBUFFERED: 1
    ports:
      - "5008:5008"



  ####################################
  # Error microservice
  ####################################  
  error:
    build:
      context: ./error
      dockerfile: error.Dockerfile
    image: vickyyqu/error:esd
    restart: always
    depends_on:
      - rabbitmq
    environment:
      rabbit_host: rabbitmq
      rabbit_port: 5672
      PYTHONUNBUFFERED: 1

  ####################################
  # Activity Log microservice
  ####################################  
  activity_log:
    build:
      context: ./activity_log
      dockerfile: activity_log.Dockerfile
    image: vickyyqu/activity_log:esd
    restart: always
    depends_on:
      - rabbitmq
    environment:
      rabbit_host: rabbitmq
      rabbit_port: 5672
      PYTHONUNBUFFERED: 1

  #######################################################################
  # Message broker microservices
  #######################################################################

  ####################################
  # RabbitMQ: The messaging broker   
  ####################################
  rabbitmq:
    image: rabbitmq:3-management
    hostname: esd-rabbit
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes: 
      - rabbitmq_data:/var/lib/rabbitmq


  ####################################
  # Kafka
  ####################################
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.2
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: confluentinc/cp-kafka:7.3.2
    container_name: broker
    ports:
    # To learn about configuring Kafka for access across networks see
    # https://www.confluent.io/blog/kafka-client-cannot-connect-to-broker-on-aws-on-docker-etc/
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

  #######################################################################
  # Complex microservices
  ####################################################################### 



  ###############################################
  # Place Item
  ###############################################
  place_item:
    build:
      context: ./complex
      dockerfile: place_item.Dockerfile
    image: vickyyqu/place_item:esd
    restart: always
    depends_on:
      - department
      - carbon_retriever
      - item
      - activity_log
      - error
      - rabbitmq
    environment:
      rabbit_host: rabbitmq
      rabbit_port: 5672
      PYTHONUNBUFFERED: 1
      department_URL: http://department:8080/department
      carbon_retriever_URL: http://carbon_retriever:5002/search
      item_URL: http://item:5000/create
    ports:
      - "3001:3001"


  ###############################################
  # Accept Item
  ###############################################
  accept_item:
    build:
      context: ./complex
      dockerfile: accept_item.Dockerfile
    image: vickyyqu/accept_item:esd
    restart: always
    depends_on:
      - department
      - item
      - activity_log
      - error
      - rabbitmq
    environment:
      rabbit_host: rabbitmq
      rabbit_port: 5672
      PYTHONUNBUFFERED: 1
      department_URL: http://department:8080/department
      item_URL: http://item:5000
      slack_URL: http://slack:5008/slack
    ports:
      - "3101:3101"


  ###############################################
  # Reject Item
  ###############################################
  reject_item:
    build:
      context: ./complex
      dockerfile: reject_item.Dockerfile
    image: vickyyqu/reject_item:esd
    restart: always
    depends_on:
      - department
      - item
      - activity_log
      - error
      - rabbitmq
    environment:
      rabbit_host: rabbitmq
      rabbit_port: 5672
      PYTHONUNBUFFERED: 1
      department_URL: http://department:8080/department
      item_URL: http://item:5000
      slack_URL: http://slack:5008/slack
    ports:
      - "3102:3102"

  
  
  #########################################
  # Get Items By Company
  ###############################################
  get_items_by_company:
    build:
      context: ./complex
      dockerfile: get_items_by_company.Dockerfile
    image: vickyyqu/get_items_by_company:esd
    restart: always
    depends_on:
      - department
      - item
      - company
      - activity_log
      - error
      - rabbitmq
    environment:
      rabbit_host: rabbitmq
      rabbit_port: 5672
      PYTHONUNBUFFERED: 1
      department_URL: http://department:8080/department
      item_URL: http://item:5000
      company_URL: http://company:5001
    ports:
      - "3003:3003"

  #########################################
  # Get Items Details
  ###############################################
  item_details:
    build:
      context: ./complex
      dockerfile: item_details.Dockerfile
    image: vickyyqu/item_details:esd
    restart: always
    depends_on:
      - department
      - item
      - company
    environment:
      department_URL: http://department:8080/department
      item_URL: http://item:5000/all
      company_URL: http://company:5001
    ports:
      - "3004:3004"